/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioLegacyRouteImport } from './routes/portfolio-legacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiClassifySectorRouteImport } from './routes/api.classify-sector'

const PortfolioLegacyRoute = PortfolioLegacyRouteImport.update({
  id: '/portfolio-legacy',
  path: '/portfolio-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassifySectorRoute = ApiClassifySectorRouteImport.update({
  id: '/api/classify-sector',
  path: '/api/classify-sector',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-legacy': typeof PortfolioLegacyRoute
  '/api/classify-sector': typeof ApiClassifySectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-legacy': typeof PortfolioLegacyRoute
  '/api/classify-sector': typeof ApiClassifySectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/portfolio-legacy': typeof PortfolioLegacyRoute
  '/api/classify-sector': typeof ApiClassifySectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/pipeline'
    | '/portfolio'
    | '/portfolio-legacy'
    | '/api/classify-sector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/pipeline'
    | '/portfolio'
    | '/portfolio-legacy'
    | '/api/classify-sector'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/pipeline'
    | '/portfolio'
    | '/portfolio-legacy'
    | '/api/classify-sector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRoute
  PortfolioLegacyRoute: typeof PortfolioLegacyRoute
  ApiClassifySectorRoute: typeof ApiClassifySectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio-legacy': {
      id: '/portfolio-legacy'
      path: '/portfolio-legacy'
      fullPath: '/portfolio-legacy'
      preLoaderRoute: typeof PortfolioLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classify-sector': {
      id: '/api/classify-sector'
      path: '/api/classify-sector'
      fullPath: '/api/classify-sector'
      preLoaderRoute: typeof ApiClassifySectorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRoute,
  PortfolioLegacyRoute: PortfolioLegacyRoute,
  ApiClassifySectorRoute: ApiClassifySectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
